

name: Testing Build Steps 

on: 
  push:
     branches:
        - test

jobs:
  build:
    name: Test Project
    runs-on: windows-latest
    steps:
      - name: Test-Setup
        shell: pwsh
        run: choco install nuget.commandline -y

